[build]
  base    = "dashboard/client"
  publish = "dashboard/client/dist"
  command = "npm run build"

[functions]
  directory                = "dashboard/client/netlify/functions"
  node_bundler             = "esbuild"
  included_files           = ["dashboard/client/netlify/functions/*.csv"]

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
